project_name: 'OCEAN_MCFA'
organism: 'human'
author: Charlotte Boys

# User defined
singularities:
  scanpy: '/mnt/sds-hd/sd22b002/projects/MichiganIgAN/workflow/envs/scanpy.0.0.5.sif'
  mofaxmetacells: '/mnt/sds-hd/sd22b002/projects/MichiganIgAN/workflow/envs/mofaxmetacells.0.0.2.sif'
  renv: '/mnt/sds-hd/sd22b002/projects/MichiganIgAN/workflow/envs/R_env.sif'

root_dir:
  Linux: /mnt/sds-hd/sd22b002/projects/OCEAN_MCFA
  Darwin: /Users/charlotteboys/GitHub/OCEAN_MCFA

# Project defined
input: 'data/OCEAN_v3_Nu_102025a_CZI.h5ad'
metadata: 'data/metadata.csv'
sample_key: 'OCEAN_MS_Exp_ID'
batch_key: 'Project1'
condition_key: 'Cohort_Manuscript'
preprocessing:
  assays: {'main_assay': 'RNA', 'slot': 'counts'}
  reductions: {'umap': 'umap'} # 'pca' also available I think
model:
  sn10xLRCluster:
    sample_subset: ['Exp18', 'Exp19', 'Exp154', 'Exp155', 'Exp2', 'Exp21', 'Exp175', 'Exp169',
      'Exp167', 'Exp84', 'Exp85', 'Exp152', 'Exp131', 'Exp109', 'Exp214', 'Exp216', 'Exp219',
      'Exp221', 'Exp226', 'Exp228', 'Exp150', 'Exp148', 'Exp146', 'Exp145', 'Exp144', 'Exp141',
      'Exp138', 'Exp135', 'Exp133', 'Exp16', 'Exp129', 'Exp128', 'Exp126', 'Exp121', 'Exp123',
      'Exp119', 'Exp117', 'Exp115', 'Exp113', 'Exp111', 'Exp1', 'Exp197', 'Exp199', 'Exp201',
        'Exp203', 'Exp206', 'Exp208', 'Exp210', 'Exp212', 'Exp185', 'Exp186', 'Exp184', 'Exp56',
        'Exp93', 'Exp46', 'Exp36', 'Exp26', 'Exp158', 'Exp139', 'Exp92', 'Exp54', 'Exp183', 'Exp45',
          'Exp25', 'Exp35', 'Exp91', 'Exp182', 'Exp15', 'Exp58', 'Exp42', 'Exp31', 'Exp30', 'Exp29',
          'Exp28', 'Exp204', 'Exp94', 'Exp12', 'Exp173', 'Exp74', 'Exp64', 'Exp60', 'Exp61', 'Exp59',
            'Exp57', 'Exp55', 'Exp8', 'Exp9', 'Exp53', 'Exp52', 'Exp51', 'Exp50', 'Exp49', 'Exp48', 'Exp47',
            'Exp44', 'Exp6', 'Exp7', 'Exp43', 'Exp41', 'Exp40', 'Exp39', 'Exp38', 'Exp37', 'Exp34', 'Exp4',
              'Exp5', 'Exp33', 'Exp32']
    drop_views: ['tPC-IC']
    groupby: 'LR_Cluster'
    min_cells: 50
    hvg: 'hvg'
    nfactors: 20
  sn10xLRCluster2:
    sample_subset: ['Exp18', 'Exp19', 'Exp154', 'Exp155', 'Exp2', 'Exp21', 'Exp175', 'Exp169',
      'Exp167', 'Exp84', 'Exp85', 'Exp152', 'Exp131', 'Exp109', 'Exp214', 'Exp216', 'Exp219',
      'Exp221', 'Exp226', 'Exp228', 'Exp150', 'Exp148', 'Exp146', 'Exp145', 'Exp144', 'Exp141',
      'Exp138', 'Exp135', 'Exp133', 'Exp16', 'Exp129', 'Exp128', 'Exp126', 'Exp121', 'Exp123',
      'Exp119', 'Exp117', 'Exp115', 'Exp113', 'Exp111', 'Exp1', 'Exp197', 'Exp199', 'Exp201',
        'Exp203', 'Exp206', 'Exp208', 'Exp210', 'Exp212', 'Exp185', 'Exp186', 'Exp184', 'Exp56',
        'Exp93', 'Exp46', 'Exp36', 'Exp26', 'Exp158', 'Exp139', 'Exp92', 'Exp54', 'Exp183', 'Exp45',
          'Exp25', 'Exp35', 'Exp91', 'Exp182', 'Exp15', 'Exp58', 'Exp42', 'Exp31', 'Exp30', 'Exp29',
          'Exp28', 'Exp204', 'Exp94', 'Exp12', 'Exp173', 'Exp74', 'Exp64', 'Exp60', 'Exp61', 'Exp59',
            'Exp57', 'Exp55', 'Exp8', 'Exp9', 'Exp53', 'Exp52', 'Exp51', 'Exp50', 'Exp49', 'Exp48', 'Exp47',
            'Exp44', 'Exp6', 'Exp7', 'Exp43', 'Exp41', 'Exp40', 'Exp39', 'Exp38', 'Exp37', 'Exp34', 'Exp4',
              'Exp5', 'Exp33', 'Exp32']
    drop_views: ['NA'] # Must be a list-like object
    groupby: 'LR_Cluster2'
    min_cells: 50
    hvg: 'hvg'
    version: 'combined_'
    nfactors: 20
clr:
  groupby: 'LR_Cluster'

